apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
      - name: zitadel
        secret:
          secretName: zitadel
      - name: config
        configMap:
          name: wurbs-config
      - name: nats-token
        secret:
          secretName: nats-dev-token
      - name: postgres
        secret:
          secretName: wurbs-postgres-app
      containers:
      - name: main
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        env:
        - name: PGHOST
          value: {{ .Values.postgres.host }}
        - name: PGPORT
          value: "{{ .Values.postgres.port }}"
        - name: PGUSER
          value: {{ .Values.postgres.user }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.password.secret }}
              key: {{ .Values.postgres.password.key }}
        - name: PGDATABASE
          value: {{ .Values.postgres.database }}
        - name: NATS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.nats.secret }}
              key: {{ .Values.nats.keys.url }}
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.nats.secret }}
              key: {{ .Values.nats.keys.password }}
        - name: WS_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.websocket.secret }}
              key: {{ .Values.websocket.keys.host }}
        - name: WS_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.websocket.secret }}
              key: {{ .Values.websocket.keys.user }}
        - name: WS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.websocket.secret }}
              key: {{ .Values.websocket.keys.password }}
        - name: WURBS_URL
          value: https://{{ .Values.host }}
        - name: PORT
          value: "{{ .Values.port }}"
        volumeMounts:
        - name: zitadel
          readOnly: true
          mountPath: "/etc/wurbs"
          subPath: token.json
        - name: config
          readOnly: true
          mountPath: "/etc/wurbs"
          subPath: config.yaml
        - name: nats-token
          readOnly: true
          mountPath: "/etc/wurbs"
          subPath: nats-token
        - name: postgres
          readOnly: true
          mountPath: "/etc/wurbs"
          subPath: postgres.json
        command:
        - wurbs-server
        - /etc/wurbs/token.json
        ports:
        - containerPort: {{ .Values.port }}
